### ISSUE TITLE
Proposal: Add the ability to specify a custom service account in the helm chart

### ISSUE THREAD

**Issue by rmb938** [openfaas/faas-netes#154]
### Summary

Currently the helm chart is hard coded to create a service account called faas-controller. This service account should only be created if rbac is set to true. Users should also be able to specify what this service account is called.

### Effort required up front

Add a value to the helm chart called `serviceAccountName` under `faasnetesd` and move the service account creation under the rbac check.

### Migration strategy / backwards-compatibility

The `serviceAccountName` value will default to `faas-controller`

**Comment by BurtonR** [comment]
Hey @rmb938, Thanks for the proposal!
Have you had a look at the proposal guidelines [here](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#i-have-a-great-idea)?

What would be the pros and cons do being able to change the name of the service account?

Derek add label: enhancement

**Comment by rmb938** [comment]
### Pros

Able to use a different service account (that is already created) when the faas-netes chart is set to rbac=false

### Cons

None, I can't think of any cons from being able to change the name

**Comment by alexellis** [comment]
Hi Ryan, thanks for proving some more information on your suggestion. We're glad that you're engaging with the project and making suggestions. 

From the contribution guide:

> What is the motivation and context?
> Pros/Cons

There are always cons - these may not be obvious but there is always a cost and complexity to changes, that's why we need to understand the *why* and the *motivation* for the change.

I guess what we're getting at is the following - the issue outlines what you want and how you think it should be done, but we're missing the *why*. Why is this change needed? Why is it important for your real-world use-case? Every change has a cost but I've not been convinced that there's a practical need for this change.

From testing it's been shown that the service account is required even if RBAC is false, that's why it's in the default configuration. If you can show otherwise, then we would consider it.

What purpose does it serve to change the name of the service account? I think you mentioned you work at Target - so I may be missing some key information about how you run your Kubernetes clusters at Target.

Additional context: any customizations in `helm` have to be offset by the complexity they could introduce and vs the static YAML files. We have to maintain YAML files for those who do not or can not use `helm`.

**Comment by alexellis** [comment]
FYI @BurtonR Derek messages have to be in their own comment.. and double-check you're in the .DEREK.yml file too.

**Comment by rmb938** [comment]
I believe I did provide motivation in my summary

```
Users should also be able to specify what this service account is called.
```

However let me provide some context. The official helm repository has some unofficial and undocumented guidelines that most if not all charts follow for RBAC. The guidelines are as follows:

1. Charts that require any RBAC must have a flag to disable the creation of these RBAC rules.
1. Any service accounts should be able to have their name set and/or changed.
1. When RBAC is off the service account does not get created as it is now assumed that the administrator will create the service account outside of the current helm chart. It is also assumed that the administrator will attach the correct role bindings to the service account.

Reference Example Charts:
https://github.com/kubernetes/charts/tree/master/stable/coredns
https://github.com/kubernetes/charts/tree/master/stable/fluent-bit

Also what cons do you see? This will be about a 10 line change and will effect nothing but the helm chart. I don't understand how there is complexity by adding one variable and moving something into an if statement.

I also disagree that this adds any complexity to your static YAML files. It is impractical to provide YAML files for every possible helm configuration. Static YAML files should be there to deploy the system in it's entirety and it is up to the administrators to modify them as needed.  

If you need a concrete use case I do have one. In a secure and trusted kubernetes deployment only administrators of the cluster are the only ones allowed to create, change, delete RBAC rules (including service accounts). Another example would be the deployment user into a namespace (the one that helm tiller may be running as) does not have permission to create RBAC things.

**Comment by alexellis** [comment]
The service account appears to be required for operation on Kubernetes, even with RBAC disabled.

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
