### ISSUE TITLE
helm installation failed on Windows

### ISSUE THREAD

**Issue by EsrefDurna** [openfaas/faas-netes#182]
PS C:\Users\Tom\Desktop\openfaas\2\faas-netes-0.4.6\chart> helm install .\openfaas.tar.gz
Error: apiVersion "rbac.authorization.k8s.io/v1beta1" in openfaas/templates/rbac.yaml is not available

OR

PS C:\Users\Tom\Desktop\openfaas\faas-netes> helm install .\chart\openfaas\
Error: apiVersion "rbac.authorization.k8s.io/v1beta1" in openfaas/templates/rbac.yaml is not available

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
docker  Version:      17.10.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
kubetnetes
* Operating System and version (e.g. Linux, Windows, MacOS):
windows 10
* Link to your project or a code example to reproduce issue:

**Comment by stefanprodan** [comment]
Hi @EsrefDurna 

What Kubernetes version do you have? Is RBAC enabled? If not install the chart without rbac.

**Comment by alexellis** [comment]
I'm confused why you are installing with a tar.gz file? We don't give that instruction in our documentation.

Can you try the official documentation and get back with additional info Stefan asked for too? https://docs.openfaas.com/deployment/kubernetes/

**Comment by EsrefDurna** [comment]
Hello @alexellis  , I tried everything on windows.
actually tar.gz was the last thing that I tried.
i think document has to be updated for windows users. for instance in windows folder paths are "\" not "/"
so below command will never work for windows users.  
$ cd faas-netes && \
kubectl apply -f ./namespaces.yml,./yaml
 
but even tho I fixed the folder paths or tried all the other options. I'm having this error
Error: apiVersion "rbac.authorization.k8s.io/v1beta1" in openfaas/templates/rbac.yaml is not available

@stefanprodan helm is working fine for other charts so I did not try to enable/disable rbac. 

Thank you so much

**Comment by alexellis** [comment]
You may be one of the only Windows users so rather than duplicate all commands we assume that most people are using Bash. If you need Bash on Windows try the "Git Bash" the comes with Git for Windows - I highly recommend it. You can then follow every tutorial without making any changes - otherwise you are right that you should interpret the commands as for. Bash and then replace `/` for `\`.

I know that faas-netes works fine with Kubernetes 1.9.x because I've been using it this week several times, so to help you further we need your exact Kubernetes distribution and your exact Kubernetes version.

**Comment by EsrefDurna** [comment]
Thank you @alexellis

**Comment by BurtonR** [comment]
@EsrefDurna have you had any luck deploying on Windows with Helm after updating your K8s version?

**Comment by alexellis** [comment]
Thanks for closing @EsrefDurna, could you update us please?

**Comment by EsrefDurna** [comment]
Hello @alexellis I switch to mac so I cannot reproduce this problem anymore.
