### ISSUE TITLE
Minikube helm install for k8s 1.9.4 fails

### ISSUE THREAD

**Issue by cliveseldon** [openfaas/faas-netes#195]
Minikube helm install fails for k8s 1.9.4 due to https://github.com/kubernetes/kubernetes/issues/61076
The error is on the prometheus and alertmanager pods.

## Possible Solution
Works on k8s 1.9.0
```
minikube start --memory 4096 --kubernetes-version v1.9.0 --extra-config=apiserver.Authorization.Mode=RBAC
```

## Steps to Reproduce (for bugs)
```
minikube start --memory 4096 --kubernetes-version v1.9.4 --extra-config=apiserver.Authorization.Mode=RBAC
kubectl create clusterrolebinding kube-system-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
kubectl -n kube-system create sa tiller  && kubectl create clusterrolebinding tiller       --clusterrole cluster-admin       --serviceaccount=kube-system:tiller
helm init --skip-refresh --upgrade --service-account tiller
kubectl create ns openfaas
kubectl create ns openfaas-fn
helm upgrade --install openfaas openfaas/    --namespace openfaas    --set functionNamespace=openfaas-fn

```

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by alexellis** [comment]
Hi,

The issue you are pointing at is a Kubernetes issue not an OpenFaaS one so I think we should close it.

Here are some suggestions which may help you:

1) A fix for the referenced issue was released by Kubernetes https://github.com/kubernetes/kubernetes/issues/61076 - make sure you have it
2) Rather than specifying `--kubernetes-version` - it may be better to use the default (latest) version to ensure you have the fix
3) The documentation recommends you use kubeadm as the initialiser for minikube (`--bootstrapper=kubeadm`

If you try all the above including updating minikube and still have issues then raise an issue with the minikube repository.

Alex

**Comment by alexellis** [comment]
Derek close: wrong repository - minikube/Kubernetes issue
