### ISSUE TITLE
Helm chart should allow configuring resource requests

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#213]
## Expected Behaviour

The Helm chart does not set nor allow setting the `resource.request` or `resource.limit` for any of the deployment objects.  Each of the deployment objects should read a corresponding `resources` value to allow the user to set/modify the requests as appropriate to their cluster.

## Current Behaviour

The resources are not set by a variable, they are not even hard coded values.

## Possible Solution

Each deployment template should include these lines

```yaml
          resources:
{{ toYaml .Values.<servicename>.resources | indent 10 }}
```
_and_ we should set default values that match the yaml files,

```
resources:
  requests:
    memory: 250Mi
  limits:
    memory: 250Mi 
```

## Context

I was creating a new openfaas cluster for benchmarking purposes and I could not configure the horizontal pod scaler because I could not set the resource requests.

**Comment by lihaiswu** [comment]
@LucasRoesler why this one is closed. How to configure resource requests in value.yaml for deployment objects?

**Comment by lihaiswu** [comment]
Looks like resource can not be configured in helm chart. Can we reopen this issue? @alexellis

**Comment by lihaiswu** [comment]
Any update on this issue? Since our kubernetes cluster has not allowed to deploy objects without resource requests, i have to update resource for all objects. I'd like to just use the helm repo and override the resource by value.yaml. 

When the fix will be merged to master? @LucasRoesler @alexellis

**Comment by alexellis** [comment]
Happy to take a PR for this @lihaiswu or for someone else in the community to pick this up.

@LucasRoesler since we started generating the Prometheus config for armhf the 512Mi request is too large and I can't deploy OpenFaaS on a 1GB RPi anymore. It'd be great to set the requests value for Prometheus in the armhf values override to 128Mi for instance.

**Comment by LucasRoesler** [comment]
Just noting, if someone wants to pick this up, 

```
          resources:
            {{- .Values.<servicename>.resources | toYaml | nindent 12 }}
```

is the best way i have seen this done.  The `nindent 12` means you can indent that block "correctly".  This would need to be added to each Deployment object and documented in the README

**Comment by lihaiswu** [comment]
I just make change, but unable to push commit to private branch. I received 403. Do I need to request any permission.
