### ISSUE TITLE
Question: good way to deploy jaeger and faas-netes

### ISSUE THREAD

**Issue by scher200** [openfaas/faas-netes#272]
Hello, does anyone maybe have a guide / tutorial about deploying jaeger and faas-netes together?

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by stefanprodan** [comment]
OpenFaaS is not instrumented with Open Tracing. Even if you deploy OF on a Istio enabled cluster, Jaeger will not be able to trace a function call as in `istio-ingressgateway-> faas-gateway -> function` since the OF Gateway doesn't forward the zipkin headers.

**Comment by ivanayov** [comment]
@alexellis said he had it working (and may be @johnmccabe )
Not sure if they have instruction written somewhere.

If you don't use it for production, but just for dev/test, this might be useful: https://github.com/jaegertracing/jaeger-kubernetes

**Comment by s8sg** [comment]
One option can be instrument it in the function `Handle()` itself. Obviously you will miss out the tracing at `gateway` part, but you can still trace your end to end`faas workflow` by passing the `span` context across `functions`. I had it working before in similar way.

**Comment by scher200** [comment]
Thank you all @ivanayov @s8sg @stefanprodan, 
I'll try the link and the Handle() function to handle this.
Though, I like the gateway traced as well, would be great if it forwards these zipkin headers. 
If @alexellis or @johnmccabe had it working, could on of them maybe post a Gist ?

**Comment by guikubivan** [comment]
Hello, any updates on this? I managed to get jaeger with elastic search running using a DaemonSet, but jaeger is installed in the `default` namespace instead of `openfaas-fn` which doesn't seem to work.

For reference, I've mostly followed the production setup (using minikube) from here https://github.com/jaegertracing/jaeger-kubernetes . That documentation worked for me when I tried a simple python container in `default` namespace (not open-faas). I just had to set the env variable JAEGER_AGENT_HOST to the ip of the node host:
```
env:
- name: JAEGER_AGENT_HOST
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

openfaas doesn't seem to support `status.hostIP`, so I tried to hard code it, but that didn't seem to work. I'm pretty new to kubernetes so I might be missing something pretty obvious. Thanks in advance!

**Comment by alexellis** [comment]
I was talking to Lucas about this topic today. Lucas have you got any ideas that might help? @lucasroesler

**Comment by guikubivan** [comment]
Or if there are other distributed tracing tools that might be preferred, I'd be interested in trying them out.

**Comment by LucasRoesler** [comment]
Right now, I think the simplest way to reach the daemonset pods is with a Service, https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods and   https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
