### ISSUE TITLE
Suggest: improve regexp.MustCompile to global init 

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [openfaas/faas-netes#288]
## Expected Behaviour

Improve `regexp.MustCompile`  to global init,  reduce unnecessary init

## Current Behaviour

Each creates a handler to create new functions need  do `ValidateDeployRequest`, `regexp.MustCompile` all need to compile,  add unnecessary init

## Possible Solution

Improve `regexp.MustCompile` to global defined, reduce `regext.MustCompile` init, performance optimization

## Context

I has open pr https://github.com/openfaas/faas-netes/pull/289  to improve

**Comment by burtonr** [comment]
@feifeiiiiiiiiiii I notice you opening several issues recently. First, thank you for taking interest in improving the project!
However, could you please fill out the issue template completely. The template is there so we can better understand the situation you have where there is an issue, or room for improvement. Having the "Current Behaviour" and "Expected Behaviour" helps knowing what you're expecting and perhaps there could be another solution.
The "Your Environment" section is also very important so that we can be able to reproduce your issue, or validate your recommendations.

Finally, please consider joining the Slack community so that discussions can happen at a faster pace and with more participants as all areas of the project are discussed together.
Sign up following the instructions here: https://docs.openfaas.com/#community

**Comment by feifeiiiiiiiiiii** [comment]
@burtonr ok, thanks suggest
