### ISSUE TITLE
Prometheus is not by default NodePorts as API Gateway in helm.

### ISSUE THREAD

**Issue by lmxia** [openfaas/faas-netes#316]
In README.md it said that:
`By default NodePorts will be created for the API Gateway and Prometheus.` which is actually not true. Prometheus is now by default ClusterIP, should we make it NodePorts?

**Comment by LucasRoesler** [comment]
The prometheus server itself is an internal component that we choose not to expose in the chart because we can not easily protect it with authentication. it is also not expected to be used directly.  

We should probably update the note in the README to remove Prometheus in that comment

**Comment by lmxia** [comment]
Well.

**Comment by jasj** [comment]
Hi, so now is imposible to get the chart that is in the main page, could you help us to recreate this chart whitouy get prometus

**Comment by LucasRoesler** [comment]
Hi @jasj i am not sure what you mean when you say that you can not get the chart from the main page, how are you trying to get it? Also, in terms of recreating a chart without Prometheus, there is a `prometheus.create` and `alertmanager.create` value that can be used to control if prometheus is installed. See the table here https://github.com/openfaas/faas-netes/tree/master/chart/openfaas

If you have additional questions about prometheus, it would be good to open a new ticket so that we can make it easier for other people to also see/search for it in the future.
