### ISSUE TITLE
Proposal: Expose SecurityContext options when deploying functions

### ISSUE THREAD

**Issue by cheeseandcereal** [openfaas/faas-netes#371]
The [Kubernetes SecurityContext API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#securitycontext-v1-core) is a great way to restrict running containers on a kubernetes system from various sorts of capabilities related to the security of the host. Exposing these to the administrator/user deploying functions would allow for the application of necessary security restrictions when running potentially un-trusted code/containers.

## Context
In an effort to work towards allowing customers (and potentially malicious code), to supply function containers, or more generally simply run un-trusted code, more options need to be available to assist in locking down/restricting function permissions.

Kubernetes already has the SecurityContext section of a container spec which is used exactly for this purpose, and simply exposing it as options on function creation would allow for restrictions such as:

- Running a function as a particular user/fsgroup (runAsUser/runAsGroup)
- Restricting containers from running as the root user inside of a container, to help prevent container breakout vulnerabilities (runAsNonRoot)
- Setting SELinux restrictions for additional security options while running on an SELinux host (seLinuxOptions)
- Restricting arbitrary [POSIX capabilities](https://linux.die.net/man/7/capabilities) from a function (capabilities)
- etc

All of these kubernetes features are great security additions that OpenFaaS could easily take advantage of when deploying functions.

I would even consider this a necessary step towards allowing unknown/potentially malicious code to be run as functions in a kubernetes OpenFaaS deployment.

## Next Steps

In order for this to happen, the api gateway accepting functions just needs to take additional data for SecurityContext, and modify the generated kubernetes deployments appropriately.

Comments or suggestions would be appreciated.

**Comment by alexellis** [comment]
Hi @cheeseandcereal would you be satisfied with this happening at a per OpenFaaS level, or do you have a hard requirement for this to be at per function level?

**Comment by cheeseandcereal** [comment]
I think for a lot of use-cases (including our own), just having this at the OpenFaaS level for all functions would suffice.

With that said, I could also see a use-case for wanting these controls on a per-function basis, especially when the goal is deploy customer (untrusted) code.

**Comment by joshuabuildsthings** [comment]
@alexellis - +1 to seeing it at the function level. For example being able to add capabilities such as CAP_NET_ADMIN to a function via SecurityContext.

**Comment by bmcstdio** [comment]
I agree this is an important feature. I would be happy if it could be implemented on a per-function basis. I could probably help where necessary, provided I can find the time for that by the time we arrive at an eventual decision.

One way I see it working is that we could introduce something like a `FunctionSecurityContextPreset` cluster-scoped custom resource definition which cluster operators could create as required, and reference that by name on a per-function basis. Thoughts?

**Comment by matzhaugen** [comment]
I would also like to see this implemented in some way.

**Comment by LucasRoesler** [comment]
Take a look at the new Profiles feature for faas-netes https://docs.openfaas.com/reference/profiles/#available-options. it allows you to define a podSecurityContext template and then add it to functions via an annotation https://docs.openfaas.com/reference/profiles/#available-options

Let me know if this works for you and then we can close this issue

**Comment by cheeseandcereal** [comment]
> Take a look at the new Profiles feature for faas-netes https://docs.openfaas.com/reference/profiles/#available-options. it allows you to define a podSecurityContext template and then add it to functions via an annotation

This seems like an appropriate solution for this issue, able to be deployed on a per-function level. I would be happy to close this issue unless anyone else objects.

**Comment by matzhaugen** [comment]
Fine with me. Looks good.

**Comment by alexellis** [comment]
Hi @cheeseandcereal can you say more about how are you using openfaas?

**Comment by cheeseandcereal** [comment]
Not sure what you mean? The catalyst for this issue was to be able to lock down functions to be able to run un-trusted containers in OpenFaaS, implementing restrictions that k8s provides.

**Comment by alexellis** [comment]
I was wondering whether we had your usecase and company/employer listed in the adopters file yet?

https://github.com/openfaas/faas/blob/master/ADOPTERS.md

**Comment by cheeseandcereal** [comment]
Oh yeah, it's already been added there a while ago

**Comment by alexellis** [comment]
👍 Which was it again?

**Comment by cheeseandcereal** [comment]
> 👍 Which was it again?

Dragonchain

**Comment by alexellis** [comment]
Aha, right. You used to sponsor, but cancelled for some reason. If you do reconsider, we have a dedicated page for the project now and a Premium Subscription for priority attention on PRs/Issues.

https://openfaas.com/support and https://github.com/sponsors/openfaas

So far only one end user company is sponsoring out of all of them. 🤔

**Comment by matzhaugen** [comment]
It seems like I cannot set `allowPrivilegeEscalation` in the podSecurityContext, but only in the (container) SecurityContext . Any reason why you decided to go with the pod security context as opposed to the container equivalent?

**Comment by LucasRoesler** [comment]
@matzhaugen the primary reason for picking Pod vs Container security context was only due to the specific use cases we were trying to enable at the time. Specifically, setting the `fsGroup`, which doesn't seem to be accessible from the container security context.  

I would not be opposed to including access to the `securityContext`

**Comment by alexellis** [comment]
Should [`allowPrivilegeEscalation`](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privilege-escalation) ever be `true`? What would happen if we permanently set it to `false`?

**Comment by alexellis** [comment]
> AllowPrivilegeEscalation - Gates whether or not a user is allowed to set the security context of a container to allowPrivilegeEscalation=true. This defaults to allowed so as to not break setuid binaries. Setting it to false ensures that no child process of a container can gain more privileges than its parent.

**Comment by matzhaugen** [comment]
I suspect the [docker-in-docker image](https://hub.docker.com/_/docker) needs `allowPrivilegeEscalation=True`, which may be a not-too-uncommon use case for faas-netes. 

In our use case, we require modification to the securityContext which we currently have a fork of faas-netes for. But we also need this fork to specify a DNS server outside the cluster due to very strict network policies (no function pods can communicate with other cluster entities), and a larger terminationGracePeriod due to large computing time on the function pods. I suspect that the latter two requirements are not in popular demand and so we will probably need this fork for the forseeable future.

**Comment by LucasRoesler** [comment]
@matzhaugen and @alexellis  there is an open PR for the DNS support that is ready to merge https://github.com/openfaas/faas-netes/pull/685

**Comment by alexellis** [comment]
> I suspect the docker-in-docker image needs allowPrivilegeEscalation=True, which may be a not-too-uncommon use case for faas-netes.

I've never heard of anyone running Docker in Docker as a function in openfaas. Is that something that you do? Can you explain what you mean there?

>  I suspect that the latter two requirements are not in popular demand and so we will probably need this fork for the forseeable future.

Your colleague Anders was consulting with OpenFaaS Ltd and felt it was beneficial to upstream features over maintaining your own fork. We offer backlog prioritisation and priority support on issues etc through our Premium Subscription. Happy to discuss whenever it suits you. https://www.openfaas.com/support/

**Comment by matzhaugen** [comment]
> I've never heard of anyone running Docker in Docker as a function in openfaas. Is that something that you do? Can you explain what you mean there?

 We don't actually use openfaas for our docker image building, so `allowPrivilegeEscalation=True` is *not* a requirement for us, it was just a use case that I thought maybe other people could have. In any case, we're not opposed to have this permanently set to `false`.

As far as removing our fork, yes that would be nice. With the DNS config PR in, we would only need our customizable `terminationGracePeriod` in the deployment. Would that be something we can include in the upstream?

**Comment by LucasRoesler** [comment]
@matzhaugen are you applying the same customizations to all functions? with profiles, you probably need some kind of admission webhook that will check and enforce that there are certain labels/annotaitons to make sure that the required function label is always set to the required profile. 

I wonder if some of these values should actually be set via flags/config in the faas-netes provider, so that they are consistenly applied regardless of the profiles selected

**Comment by matzhaugen** [comment]
We actually control the profile on the back-end. Because we have built a interface on top of OpenFaas, users do not need to know about OpenFaas or profiles. As of now, we apply one profile to all functions, setting the necessary tolerations for our node pools etc, but we would like to set the container security context as well. But this is all independent of the `terminationGracePeriod` of pods, though, which we have at 15 minutes to support long running functions. It seems like this variable is unique to kubernetes and would be best put in the profile as well? But somehow it seems a bit too specific/technical for profile's use case. Ideally, this variable would mirror [write_timeout](https://docs.openfaas.com/deployment/troubleshooting/#timeouts-gateway) in the gateway, right? But I understand that the gateway should be agnostic of the provider, so I am not sure what an elegant solution to this is.

**Comment by LucasRoesler** [comment]
@matzhaugen if you are using the openfaas operator, then you could enforce labels on functions via a mutation webhook. Similarly for the terminationGracePeriod, if the pod has a certain label then add the grace period via the mutation. This would allow you to get the same effects without any patches. It effectively moves the patches into a webhook/middleware  that is independent of openfaas

**Comment by alexellis** [comment]
terminationGracePeriod sounds useful for other users, we have talked about using a prestop hook in the past. I think this should be on the backlog, but prioritising that over other work is going to be the issue. Good suggestion @LucasRoesler on temporary workarounds.
