### ISSUE TITLE
Potential issues with AlertManager

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#372]
## Expected Behaviour

Given a stable load from `hey` such as `-c 2 -q 10 -n 100000` into the `echo-go` function, I would expect to see a steady rate of increase on gateway invocations and in the service count.

## Current Behaviour

* Sometimes AlertManager continues to fire alerts, even after the Alert is cleared in the Alerts tab in Prometheus
* Sometimes the Alert appears to be stuck as "Pending"
* Sometimes the resolved alert is taking much longer than usual to fire
* Sometimes the Alert has hysteresis and is firing/resolving continually instead of steadily increasing the replica count. 

I believe this was introduced between 1.8.1 and 1.9.1 of the helm chart.

<img width="1679" alt="screenshot 2019-02-16 at 11 13 12" src="https://user-images.githubusercontent.com/6358735/52899323-a90abf80-31e0-11e9-893c-de78b5021720.png">

Kubeadm / 1.13 single node

<img width="595" alt="screenshot 2019-02-16 at 11 21 07" src="https://user-images.githubusercontent.com/6358735/52899325-b32cbe00-31e0-11e9-87f8-6db2e376d01c.png">

Swarm

## Investigate

Test each version with `kind` or similar using a script for a repeatable environment, until we can figure out what changed / went wrong.

Compare to Swarm

Changes and variables:

* Prometheus version upgraded https://github.com/openfaas/faas-netes/commit/37108946eb8352c200eed2c893ab2041e76cba43
* Basic auth for /system/alert added and AlertManager configs updated for this https://github.com/openfaas/faas-netes/pull/357
* Kubernetes SD enabled for Pod scraping by Prometheus https://github.com/openfaas/faas-netes/pull/363

Not changed:

* AlertManager *not* upgraded, 0.16.1 is available with many changes since 0.15.0 that we are using now.

Prom queries:

```
sum by(function_name) (rate(gateway_function_invocation_total{code="200"}[10s]))

gateway_service_count

http_requests_total{path="/system/alert"}
```

Loading:

```
git clone https://github.com/alexellis/echo-fn
faas-cli deploy -g ...

hey -c 2 -q 10 -n 10000 http://127.0.0.1:8080/function/go-echo

```

Port-forwarding:

```
kubectl port-forward svc/prometheus -n openfaas 9090:9090
```

**Comment by rgee0** [comment]
Behaviour of 1.8.1 helm chart:

![image](https://user-images.githubusercontent.com/16418793/52900412-508def00-31ed-11e9-9170-abe6ca803aca.png)

**Comment by alexellis** [comment]
Thanks Richard.

Here is an idea to narrow things down:

What happens if you update the Prometheus deployment image but keep the rest the same?

**Comment by rgee0** [comment]
Behaviour of 1.8.1 helm chart after moving to `prom/prometheus:v2.7.1`:
![image](https://user-images.githubusercontent.com/16418793/52901568-30fec280-31fd-11e9-9ad0-d2adb972929e.png)

**Comment by LucasRoesler** [comment]
This is a my first test of the `1.9.1` helm chart  but overriding prometheus to `prom/prometheus:v2.3.1`
![image](https://user-images.githubusercontent.com/891889/52901604-0402dd80-3206-11e9-907c-c180bcb880c5.png)

**Comment by rgee0** [comment]
Behaviour of the 1.9.1 helm chart with `prom/prometheus:v2.4.0`:
![image](https://user-images.githubusercontent.com/16418793/52902030-eaac6200-3202-11e9-829d-9587f4c07af8.png)

**Comment by rgee0** [comment]
Behaviour of the 1.9.1 helm chart with `prom/prometheus:v2.5.0`:
![image](https://user-images.githubusercontent.com/16418793/52904644-adf26200-3226-11e9-8e3e-7869ffac5cec.png)

Swarm running `prom/prometheus:v2.7.0`:
![image](https://user-images.githubusercontent.com/16418793/52904659-e2661e00-3226-11e9-9570-fcb5a4061e84.png)

Swarm running `prom/prometheus:v2.7.1`:
![image](https://user-images.githubusercontent.com/16418793/52904670-032e7380-3227-11e9-8bd0-f830c11d2b8a.png)

**Comment by LucasRoesler** [comment]
In summary, I have tried every released version of Prometheus from 2.3.1 -- 2.7.1 and only version 2.3.1 seems to work as expected (function scales up underload and then quickly scales down when the load stops) 

With each other version I saw issues with scaling not being triggered because the alert was stuck in pending and never fired or resolution would lag, meaning the alert handler received alerts saying that the scaling alert was firing for 3 --4 mins after the alert in prometheus was resolved. 

While searching for potentially related issues I found prometheus/prometheus#4836 and the related mailing list discussion https://groups.google.com/d/msg/prometheus-users/7Ul6ngc7Ogs/j_YDszV5BwAJ the alert value should not be included in the alert labels otherwise each calculation of the alert is treated like a new alert and then the use of `for 5s` will not behave as expected.  I have tested removing the alert value from the label in 2.7.1 and scaling up worked as expected but I still saw the issue with lagging resolution.

**Comment by alexellis** [comment]
Thank you for sharing your findings Lucas. I spoke with @juliusv, he suggested that we try combining Prometheus with the latest version of AlertManager which is 0.16.1. Please could you find out whether that resolves the issues we've seen along with your other change?

**Comment by LucasRoesler** [comment]
Sure, of course.

**Comment by juliusv** [comment]
The lag in resolution may just be the configured group_wait interval. Once all alerts in a group in Alertmanager have been resolved, it may take up to that long for the resolved notification to be sent out.

Still, there were some Alertmanager issues that were fixed in recent versions, so it's a good idea to use the latest.

**Comment by LucasRoesler** [comment]
The behavior seems 100% normal when both prometheus and alert manager are upgraded together

The image below shows the throughput, alert status, and then replica count.  You can see it clearly ending as expected.

![image](https://user-images.githubusercontent.com/891889/52916956-e6a54080-32e5-11e9-895f-74dd2f29159b.png)

The plateau on the replicas is the configured max count.

**Comment by alexellis** [comment]
Derek lock
