### ISSUE TITLE
Allow taililing of a numer of log lines without specifying a time period

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/faas-netes#548]
It would be good to be able to tail a certain number of lines without specifying a "since" argument, currently you need to specify since, or it defaults to 5 minutes and you might not get the numer of lines you requested.

## Expected Behaviour

--tail does not need a --since time that returns enough lines to tail. 

## Current Behaviour

Tailing a number of lines depends on that number of lines returned in the time period specified, or 5 minutes if not specified.

## Possible Solution

If the tail argument is sent, without a since, or since-time then we need to get that number of lines, or get all lines if that many dont exist.

## Context

Ofc cloud logs have been surfaced to dashboard and people want a certain number of lines sent back without them being within a certain time period.

**Comment by Waterdrips** [comment]
/ assign: me

**Comment by rajatjindal** [comment]
Hey Alex/Alistair

I am trying my hands on fixing this today. I've few questions:

- currently logs function accepts param 'since' in RFC3339 format. do you think it will be ok to add another parameter sinceDuration which can be a duration like 15m, 1h?
- the function [GetLogs](https://github.com/openfaas/faas-netes/blob/master/k8s/logs.go#L56) , it has all required options as function parameters. Do you think it will be fine if we pull these params in a GetLogsRequest struct?

**Comment by rajatjindal** [comment]
opened PR with just the change to allow tail and since to be used exclusively https://github.com/openfaas/faas-netes/pull/554

**Comment by alexellis** [comment]
We should be using the closes keyboard in the PRs, that automatically closes them. Cc @rgee0 

Rajat FYI you can't use Derek at the moment - the access list is controlled through the main repo in the .DEREK.yml file. If you think that you will be helping us out over the next few months at least then feel free to add yourself.

**Comment by rgee0** [comment]
I was almost certain use of closure keywords was in the `contributing.md` file.  Cant see it now.
