### ISSUE TITLE
Proposal: CRD/controller to manage functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#70]
Create a CRD custom resource definition which represents the Function abstraction. Plus controller to reconcile the state.

A Function would internally create the existing pair of:

* Service
* Deployment

The faas-netesd controller would be responsible for accepting the Function definition via the existing RESTful API. Then rather than creating/updating/deleting services and deployments we'd create/update/delete Functions.

The controller would then be responsible for CRUD on Services/Deployments.

Other concerns include:
- migration to users with existing deployments of OpenFaaS
- maintaining backwards compatibility - i.e. what is the minimum version CRDs become available?
- maintaining a least-privilege scope for RBAC

## Status

Level: advanced
Status: design/PoC

## Initial work / artifacts

Initial work / artifacts should begin to define and scope the work only.

Please create architectural diagrams to support design.

**Comment by jgensler8** [comment]
Hey @alexellis,

I have implemented a Controller for OpenFaaS definitions: https://github.com/jgensler8/openfaas-controller

To do so, I have generated and committed a go-client library for OpenFaaS: https://github.com/jgensler8/openfaas-client-go

Definitions look like the following:
```yaml
apiVersion: "jgensler8.openfaas.apiextensions.k8s.io/v1"
kind: "Function"
metadata:
  name: "samplefunction"
spec:
  service: "myservicetwo"
  image: "nginx:1.13"
  envVars: []
  envProcess: ""
  registryAuth: ""
  network: ""
```

As you can see, the `apiversion` should probably change to something more "official." Perhaps referencing other projects (like [Istio](https://github.com/istio/istio/blob/9f920e2f4ac09f8771834dbea322e57c2648f081/mixer/cmd/mixs/cmd/crd_test.go#L45)) could help with deciding a proper [group](https://github.com/jgensler8/openfaas-controller/blob/v0.1.0/pkg/apis/cr/register.go#L20)

In terms of using the generated go client library, I think there is some overlap with https://github.com/openfaas/faas/issues/214 as the names of the CRUD functions look like [`SystemFunctionsPut`](https://github.com/jgensler8/openfaas-controller/blob/v0.1.0/pkg/controller/controller.go#L119) instead of `UpdateSystemFunctions` or `UpdateFunction`

Let me know what you think of the initial design as well as moving the go-client library elsewhere.

Regards,
Jeff

**Comment by alexellis** [comment]
@stefanprodan has started to do a spike on this at https://github.com/openfaas-incubator/faas-o6s

Stefan can you update this issue with the discussion from the yesterday around versioning and migration.

@jgensler8 thanks for spending some time looking into this. Do we have you in the Slack community yet?

**Comment by jgensler8** [comment]
@alexellis I am not in the Slack Channel yet. I'll tweet or email in the next day or so.

**Comment by alexellis** [comment]
Work is in progress on this. cc @jgensler8

**Comment by BurtonR** [comment]
@stefanprodan Could you share a little about what you've done with this?
I see it's implemented on openfaas-operator here: https://github.com/openfaas-incubator/openfaas-operator/pull/8

Is there any chance of that getting ported back here?

**Comment by stefanprodan** [comment]
I would deprecate the current faas-netes code, move it to a branch and copy the openfaas-operator code into faas-netes master. The downside to this would be breaking compatibility with Kubernetes 1.7

**Comment by alexellis** [comment]
faas-netes is stable and openfaas-operator is alpha, it needs testing and exposure which we are planning to do through allowing people to install it with Helm.

This issue should stay open to track the progress of above.

**Comment by alexellis** [comment]
Ping to @jgensler8 - please could you take a look at our operator and kick the tires?

**Comment by jgensler8** [comment]
@alexellis I don't think I'll have time to look at your operator. I have explored non-Kubernetes options as the cost of hosting Kubernetes was too much for my side project.

**Comment by alexellis** [comment]
You can host on a single node VPS for less than $5/month

**Comment by alexellis** [comment]
@stefanprodan what thoughts do you have on the new operator framework/SDK via CoreOS/RedHat? Pros/cons? https://github.com/operator-framework

**Comment by alexellis** [comment]
Derek close: released as OpenFaaS Operator

**Comment by alexellis** [comment]
Derek lock
