### ISSUE TITLE
Question about gateway_function_invocation_total metric

### ISSUE THREAD

**Issue by bansaltushar92** [openfaas/faas-netes#748]
## Expected Behaviour
A way to filter the the health check invocations from the **gateway_function_invocation_total** metric. Add either the "path" to the gateway_function_invocation_total or add another metric that doesn't count invocations to the health check endpoint (/_/health).

## Current Behaviour
The **gateway_function_invocation_total** metric is a counter of total invocation requests for a particular function. Since it doesn't contain the information about the path of the invocations, it is not possible to filter the invocations that were simply regular health checks (to /_/health) from actual requests to the function execution itself.

## Possible Solution
Add either the "path" to the gateway_function_invocation_total or add another metric that doesn't count invocations to the health check endpoint (/_/health).

**Comment by alexellis** [comment]
/set title: [Feature request] Remove health check HTTP calls from metrics

**Comment by bansaltushar92** [comment]
@alexellis If anyone can guide me on the approach, I can take an attempt at it.

**Comment by alexellis** [comment]
I am confused how to reproduce the issue, can you show some evidence like metrics, or screenshots that show that the watchdog component's health endpoint is being tracked in the `gateway_function_invocation_total` metric?

`gateway_function_invocation_total ` is tracked at the gateway and I can't think of any component that would deliberately call each function URL and `/_/health`.

**Comment by alexellis** [comment]
/set title: Question about gateway_function_invocation_total metric

**Comment by alexellis** [comment]
@bansaltushar92 please see the comments that I have sent you here.

**Comment by bansaltushar92** [comment]
@alexellis Here's an example of this metric value in prometheus. One of our monitoring service sends periodic requests to the gateway on endpoint `/function/{function_name}/_/health` to check the health of the deployment. However, this gets counted in the `gateway_function_invocation_total` metric and there is no way for us to differentiate on basis of this metric whether this was a health check request or to the function itself.

![image](https://user-images.githubusercontent.com/23127273/107453481-e9675480-6aff-11eb-9509-cff1a9849db9.png)

* All requests in the image above are health check requests.

**Comment by alexellis** [comment]
This is non-standard behaviour, which is not part of the OpenFaaS codebase, so falls outside of the scope of how we can help you. There is no need for you to make these HTTP calls to _health because Kubernetes is already configured to do it.

My question is - why did you deem it necessary to take this approach? What benefit or problem do you believe you're getting from it?

**Comment by bansaltushar92** [comment]
Thanks for the update. Our monitoring service send these requests to _health endpoint at a regular interval to ensure that the functions are in a healthy state. If we don't receive a success response, it'll send alerts to the stakeholders.

**Comment by alexellis** [comment]
1) That isn't required, because Kubernetes does this already and will remediate the pods
2) Each pod exposes its own _health endpoint that you can configure Prometheus to scrape, which will not affect the gateway statistics

Because you're using this for work and you have a rather complicated use-case, I'd  be open to talking you through how to set this up on a call. Click "Book now" at https://openfaas.com/support/
