### ISSUE TITLE
Question: How to set the resource limits for every function instance?

### ISSUE THREAD

**Issue by moonBirdKiss** [openfaas/faas-netes#837]
Hello. For the Serverless functions, there is an import feature that every function instance can have a specific resource limit. But I find the function instances are executed in the same Pod in OpenFaas(based on Kubernetes). And I find we can only use `request` and `limit` provided by Kubernetes. However, all the instances are sharing these resources.
Is there any way that I can allocate a CPU for each function instance?

Here is the link: [Function: Memory/CPU limits: OpenFaas](https://docs.openfaas.com/reference/yaml/#function-memorycpu-limits)

Thank you a lot.

**Comment by moonBirdKiss** [comment]
Please help, thanks again.

**Comment by LucasRoesler** [comment]
Hi @moonBirdKiss i am a little confused by the question. The documentation you linked is exactly what you need. For each function, you need to specify the resource requests and limits, to ensure 1 cpu per instance you need to use

```yaml
requests:
      cpu: 1
```

When running on kubernetes, each instance will be its own Pod, so each instance will get it's own CPU, assuming the cluster is big enough. 

If you are seeing different behavior then you will need to open a (new) bug report explaining how your cluster was setup, how you  deployed openfaas, and an example function so that we can attempt to reproduce and debug the issue.

**Comment by moonBirdKiss** [comment]
thank you. And I find a way to solve my problem.
